### PR TITLE
EY review

### PR DESCRIPTION
**Pull request by edoyango**
Starting my review.

First change is the addition of a workflow summary print.

### CODE REVIEW

**Comment by edoyango** [comment]
@jIskCoder can you please review?
* Standardised comments and spacing a bit
* Removed `cleanup = true` in the Milton profile.
    * `cleanup = true` removes resumability and is redundant on Milton, where VAST scratch is default and has automatic cleanup.
* Added a completion message
* fixed the `csplit`/`gcsplit` selection. It was the wrong way around.

**Comment by jIskCoder** [comment]
Are you sure about csplit/gcsplit selection?
It worked fine on Milton and I copied it from a tutorial https://www.nextflow.io/docs/latest/example.html

@edoyango

**Comment by jIskCoder** [comment]
Found it https://www.nextflow.io/docs/latest/example.html

**Review by jIskCoder — COMMENTED** [review]
https://www.nextflow.io/docs/latest/example.html

**Comment by edoyango** [comment]
> Are you sure about csplit/gcsplit selection? It worked fine on Milton and I copied it from a tutorial https://www.nextflow.io/docs/latest/example.html
> 
> @edoyango

sorry yep you're right. My mac has `csplit` not `gcsplit`, so not sure if the if else is needed. do you have `csplit` on your mac? Maybe we should exclude it?

**Pull request merged**
